// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: myFirstGrpcPackage.proto

//命名空间

package myFirstGrpcPackage

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//普通rpc
// demo one request
type RequestDemoOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RequestDemoOne) Reset() {
	*x = RequestDemoOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDemoOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDemoOne) ProtoMessage() {}

func (x *RequestDemoOne) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDemoOne.ProtoReflect.Descriptor instead.
func (*RequestDemoOne) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{0}
}

func (x *RequestDemoOne) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//demo one response
type ResponseDemoOne struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseDemoOne) Reset() {
	*x = ResponseDemoOne{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDemoOne) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDemoOne) ProtoMessage() {}

func (x *ResponseDemoOne) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDemoOne.ProtoReflect.Descriptor instead.
func (*ResponseDemoOne) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseDemoOne) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseDemoOne) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//服务端流rpc
// demo two request
type RequestDemoTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RequestDemoTwo) Reset() {
	*x = RequestDemoTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDemoTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDemoTwo) ProtoMessage() {}

func (x *RequestDemoTwo) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDemoTwo.ProtoReflect.Descriptor instead.
func (*RequestDemoTwo) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{2}
}

func (x *RequestDemoTwo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//demo two response
type ResponseDemoTwo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseDemoTwo) Reset() {
	*x = ResponseDemoTwo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDemoTwo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDemoTwo) ProtoMessage() {}

func (x *ResponseDemoTwo) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDemoTwo.ProtoReflect.Descriptor instead.
func (*ResponseDemoTwo) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseDemoTwo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseDemoTwo) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//客户端流rpc
// demo three request
type RequestDemoThree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RequestDemoThree) Reset() {
	*x = RequestDemoThree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDemoThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDemoThree) ProtoMessage() {}

func (x *RequestDemoThree) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDemoThree.ProtoReflect.Descriptor instead.
func (*RequestDemoThree) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{4}
}

func (x *RequestDemoThree) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//demo three response
type ResponseDemoThree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseDemoThree) Reset() {
	*x = ResponseDemoThree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDemoThree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDemoThree) ProtoMessage() {}

func (x *ResponseDemoThree) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDemoThree.ProtoReflect.Descriptor instead.
func (*ResponseDemoThree) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseDemoThree) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseDemoThree) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

//双向流rpc
// demo four request
type RequestDemoFour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RequestDemoFour) Reset() {
	*x = RequestDemoFour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDemoFour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDemoFour) ProtoMessage() {}

func (x *RequestDemoFour) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDemoFour.ProtoReflect.Descriptor instead.
func (*RequestDemoFour) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{6}
}

func (x *RequestDemoFour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//demo four response
type ResponseDemoFour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ResponseDemoFour) Reset() {
	*x = ResponseDemoFour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_myFirstGrpcPackage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDemoFour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDemoFour) ProtoMessage() {}

func (x *ResponseDemoFour) ProtoReflect() protoreflect.Message {
	mi := &file_myFirstGrpcPackage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDemoFour.ProtoReflect.Descriptor instead.
func (*ResponseDemoFour) Descriptor() ([]byte, []int) {
	return file_myFirstGrpcPackage_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseDemoFour) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseDemoFour) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_myFirstGrpcPackage_proto protoreflect.FileDescriptor

var file_myFirstGrpcPackage_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x6d, 0x79, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x24,
	0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x6e, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x24, 0x0a,
	0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x77, 0x6f, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44,
	0x65, 0x6d, 0x6f, 0x54, 0x77, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x26, 0x0a, 0x10,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x68, 0x72, 0x65, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x6d, 0x6f, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x25, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x6f,
	0x75, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x6f, 0x75, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0xee, 0x02, 0x0a, 0x03, 0x47, 0x79, 0x6d, 0x12, 0x54, 0x0a, 0x07, 0x44, 0x65, 0x6d, 0x6f,
	0x4f, 0x6e, 0x65, 0x12, 0x22, 0x2e, 0x6d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x6e, 0x65, 0x1a, 0x23, 0x2e, 0x6d, 0x79, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x4f, 0x6e, 0x65, 0x22, 0x00, 0x12, 0x56,
	0x0a, 0x07, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x77, 0x6f, 0x12, 0x22, 0x2e, 0x6d, 0x79, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x77, 0x6f, 0x1a, 0x23, 0x2e,
	0x6d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x54,
	0x77, 0x6f, 0x22, 0x00, 0x30, 0x01, 0x12, 0x5c, 0x0a, 0x09, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x68,
	0x72, 0x65, 0x65, 0x12, 0x24, 0x2e, 0x6d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x47, 0x72, 0x70,
	0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6d, 0x6f, 0x54, 0x68, 0x72, 0x65, 0x65, 0x1a, 0x25, 0x2e, 0x6d, 0x79, 0x46, 0x69,
	0x72, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x54, 0x68, 0x72, 0x65, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x5b, 0x0a, 0x08, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x6f, 0x75, 0x72,
	0x12, 0x23, 0x2e, 0x6d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x47, 0x72, 0x70, 0x63, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6d,
	0x6f, 0x46, 0x6f, 0x75, 0x72, 0x1a, 0x24, 0x2e, 0x6d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x47,
	0x72, 0x70, 0x63, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x65, 0x6d, 0x6f, 0x46, 0x6f, 0x75, 0x72, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_myFirstGrpcPackage_proto_rawDescOnce sync.Once
	file_myFirstGrpcPackage_proto_rawDescData = file_myFirstGrpcPackage_proto_rawDesc
)

func file_myFirstGrpcPackage_proto_rawDescGZIP() []byte {
	file_myFirstGrpcPackage_proto_rawDescOnce.Do(func() {
		file_myFirstGrpcPackage_proto_rawDescData = protoimpl.X.CompressGZIP(file_myFirstGrpcPackage_proto_rawDescData)
	})
	return file_myFirstGrpcPackage_proto_rawDescData
}

var file_myFirstGrpcPackage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_myFirstGrpcPackage_proto_goTypes = []interface{}{
	(*RequestDemoOne)(nil),    // 0: myFirstGrpcPackage.RequestDemoOne
	(*ResponseDemoOne)(nil),   // 1: myFirstGrpcPackage.ResponseDemoOne
	(*RequestDemoTwo)(nil),    // 2: myFirstGrpcPackage.RequestDemoTwo
	(*ResponseDemoTwo)(nil),   // 3: myFirstGrpcPackage.ResponseDemoTwo
	(*RequestDemoThree)(nil),  // 4: myFirstGrpcPackage.RequestDemoThree
	(*ResponseDemoThree)(nil), // 5: myFirstGrpcPackage.ResponseDemoThree
	(*RequestDemoFour)(nil),   // 6: myFirstGrpcPackage.RequestDemoFour
	(*ResponseDemoFour)(nil),  // 7: myFirstGrpcPackage.ResponseDemoFour
}
var file_myFirstGrpcPackage_proto_depIdxs = []int32{
	0, // 0: myFirstGrpcPackage.Gym.DemoOne:input_type -> myFirstGrpcPackage.RequestDemoOne
	2, // 1: myFirstGrpcPackage.Gym.DemoTwo:input_type -> myFirstGrpcPackage.RequestDemoTwo
	4, // 2: myFirstGrpcPackage.Gym.DemoThree:input_type -> myFirstGrpcPackage.RequestDemoThree
	6, // 3: myFirstGrpcPackage.Gym.DemoFour:input_type -> myFirstGrpcPackage.RequestDemoFour
	1, // 4: myFirstGrpcPackage.Gym.DemoOne:output_type -> myFirstGrpcPackage.ResponseDemoOne
	3, // 5: myFirstGrpcPackage.Gym.DemoTwo:output_type -> myFirstGrpcPackage.ResponseDemoTwo
	5, // 6: myFirstGrpcPackage.Gym.DemoThree:output_type -> myFirstGrpcPackage.ResponseDemoThree
	7, // 7: myFirstGrpcPackage.Gym.DemoFour:output_type -> myFirstGrpcPackage.ResponseDemoFour
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_myFirstGrpcPackage_proto_init() }
func file_myFirstGrpcPackage_proto_init() {
	if File_myFirstGrpcPackage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_myFirstGrpcPackage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDemoOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDemoOne); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDemoTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDemoTwo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDemoThree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDemoThree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDemoFour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_myFirstGrpcPackage_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDemoFour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_myFirstGrpcPackage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_myFirstGrpcPackage_proto_goTypes,
		DependencyIndexes: file_myFirstGrpcPackage_proto_depIdxs,
		MessageInfos:      file_myFirstGrpcPackage_proto_msgTypes,
	}.Build()
	File_myFirstGrpcPackage_proto = out.File
	file_myFirstGrpcPackage_proto_rawDesc = nil
	file_myFirstGrpcPackage_proto_goTypes = nil
	file_myFirstGrpcPackage_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GymClient is the client API for Gym service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GymClient interface {
	//普通rpc
	DemoOne(ctx context.Context, in *RequestDemoOne, opts ...grpc.CallOption) (*ResponseDemoOne, error)
	//服务端流rpc
	DemoTwo(ctx context.Context, in *RequestDemoTwo, opts ...grpc.CallOption) (Gym_DemoTwoClient, error)
	//客户端流rpc
	DemoThree(ctx context.Context, opts ...grpc.CallOption) (Gym_DemoThreeClient, error)
	//双向流rpc
	DemoFour(ctx context.Context, opts ...grpc.CallOption) (Gym_DemoFourClient, error)
}

type gymClient struct {
	cc grpc.ClientConnInterface
}

func NewGymClient(cc grpc.ClientConnInterface) GymClient {
	return &gymClient{cc}
}

func (c *gymClient) DemoOne(ctx context.Context, in *RequestDemoOne, opts ...grpc.CallOption) (*ResponseDemoOne, error) {
	out := new(ResponseDemoOne)
	err := c.cc.Invoke(ctx, "/myFirstGrpcPackage.Gym/DemoOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gymClient) DemoTwo(ctx context.Context, in *RequestDemoTwo, opts ...grpc.CallOption) (Gym_DemoTwoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gym_serviceDesc.Streams[0], "/myFirstGrpcPackage.Gym/DemoTwo", opts...)
	if err != nil {
		return nil, err
	}
	x := &gymDemoTwoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Gym_DemoTwoClient interface {
	Recv() (*ResponseDemoTwo, error)
	grpc.ClientStream
}

type gymDemoTwoClient struct {
	grpc.ClientStream
}

func (x *gymDemoTwoClient) Recv() (*ResponseDemoTwo, error) {
	m := new(ResponseDemoTwo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gymClient) DemoThree(ctx context.Context, opts ...grpc.CallOption) (Gym_DemoThreeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gym_serviceDesc.Streams[1], "/myFirstGrpcPackage.Gym/DemoThree", opts...)
	if err != nil {
		return nil, err
	}
	x := &gymDemoThreeClient{stream}
	return x, nil
}

type Gym_DemoThreeClient interface {
	Send(*RequestDemoThree) error
	CloseAndRecv() (*ResponseDemoThree, error)
	grpc.ClientStream
}

type gymDemoThreeClient struct {
	grpc.ClientStream
}

func (x *gymDemoThreeClient) Send(m *RequestDemoThree) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gymDemoThreeClient) CloseAndRecv() (*ResponseDemoThree, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResponseDemoThree)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gymClient) DemoFour(ctx context.Context, opts ...grpc.CallOption) (Gym_DemoFourClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Gym_serviceDesc.Streams[2], "/myFirstGrpcPackage.Gym/DemoFour", opts...)
	if err != nil {
		return nil, err
	}
	x := &gymDemoFourClient{stream}
	return x, nil
}

type Gym_DemoFourClient interface {
	Send(*RequestDemoFour) error
	Recv() (*ResponseDemoFour, error)
	grpc.ClientStream
}

type gymDemoFourClient struct {
	grpc.ClientStream
}

func (x *gymDemoFourClient) Send(m *RequestDemoFour) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gymDemoFourClient) Recv() (*ResponseDemoFour, error) {
	m := new(ResponseDemoFour)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GymServer is the server API for Gym service.
type GymServer interface {
	//普通rpc
	DemoOne(context.Context, *RequestDemoOne) (*ResponseDemoOne, error)
	//服务端流rpc
	DemoTwo(*RequestDemoTwo, Gym_DemoTwoServer) error
	//客户端流rpc
	DemoThree(Gym_DemoThreeServer) error
	//双向流rpc
	DemoFour(Gym_DemoFourServer) error
}

// UnimplementedGymServer can be embedded to have forward compatible implementations.
type UnimplementedGymServer struct {
}

func (*UnimplementedGymServer) DemoOne(context.Context, *RequestDemoOne) (*ResponseDemoOne, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoOne not implemented")
}
func (*UnimplementedGymServer) DemoTwo(*RequestDemoTwo, Gym_DemoTwoServer) error {
	return status.Errorf(codes.Unimplemented, "method DemoTwo not implemented")
}
func (*UnimplementedGymServer) DemoThree(Gym_DemoThreeServer) error {
	return status.Errorf(codes.Unimplemented, "method DemoThree not implemented")
}
func (*UnimplementedGymServer) DemoFour(Gym_DemoFourServer) error {
	return status.Errorf(codes.Unimplemented, "method DemoFour not implemented")
}

func RegisterGymServer(s *grpc.Server, srv GymServer) {
	s.RegisterService(&_Gym_serviceDesc, srv)
}

func _Gym_DemoOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDemoOne)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GymServer).DemoOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/myFirstGrpcPackage.Gym/DemoOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GymServer).DemoOne(ctx, req.(*RequestDemoOne))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gym_DemoTwo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestDemoTwo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GymServer).DemoTwo(m, &gymDemoTwoServer{stream})
}

type Gym_DemoTwoServer interface {
	Send(*ResponseDemoTwo) error
	grpc.ServerStream
}

type gymDemoTwoServer struct {
	grpc.ServerStream
}

func (x *gymDemoTwoServer) Send(m *ResponseDemoTwo) error {
	return x.ServerStream.SendMsg(m)
}

func _Gym_DemoThree_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GymServer).DemoThree(&gymDemoThreeServer{stream})
}

type Gym_DemoThreeServer interface {
	SendAndClose(*ResponseDemoThree) error
	Recv() (*RequestDemoThree, error)
	grpc.ServerStream
}

type gymDemoThreeServer struct {
	grpc.ServerStream
}

func (x *gymDemoThreeServer) SendAndClose(m *ResponseDemoThree) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gymDemoThreeServer) Recv() (*RequestDemoThree, error) {
	m := new(RequestDemoThree)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Gym_DemoFour_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GymServer).DemoFour(&gymDemoFourServer{stream})
}

type Gym_DemoFourServer interface {
	Send(*ResponseDemoFour) error
	Recv() (*RequestDemoFour, error)
	grpc.ServerStream
}

type gymDemoFourServer struct {
	grpc.ServerStream
}

func (x *gymDemoFourServer) Send(m *ResponseDemoFour) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gymDemoFourServer) Recv() (*RequestDemoFour, error) {
	m := new(RequestDemoFour)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Gym_serviceDesc = grpc.ServiceDesc{
	ServiceName: "myFirstGrpcPackage.Gym",
	HandlerType: (*GymServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DemoOne",
			Handler:    _Gym_DemoOne_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DemoTwo",
			Handler:       _Gym_DemoTwo_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DemoThree",
			Handler:       _Gym_DemoThree_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DemoFour",
			Handler:       _Gym_DemoFour_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "myFirstGrpcPackage.proto",
}
